### ISSUE TITLE
Doctrine DBAL 2.5 Breaks Symfony if DB Doesn't Exist

### ISSUE THREAD

**Issue by mattjanssen** [symfony/symfony-standard#748]
This is a problem with the most recent symfony-standard.

With the newest Doctrine DBAL 2.5, Doctrine introduced `Doctrine\DBAL\Connection::detectDatabasePlatform()` which is different than 2.4. Now in 2.5, any time a repository is instantiated (not even used) by the DI, we get a PDOException if the DB doesn't already exist.

Imagine trying to run `app/console doctrine:database:create` and getting a "Database doesn't exist!" error. Repositories as services are very common in most projects, so this is a huge issue.

To reproduce quickly, create a fresh Symfony project, letting composer install the AcmeDemoBundle. Use all default parameters. Now try to generate an entity. You'll get a PDOException. This is a new regression.
```
composer create-project symfony/framework-standard-edition symfony-standard
cd symfony-standard
app/console doctrine:generate:entity --entity=AcmeDemoBundle:Foo
```
You get error this on every OS/distro/platform:
```
  [Doctrine\DBAL\Exception\ConnectionException]
  An exception occured in driver: SQLSTATE[HY000] [1049] Unknown database 'symfony'

  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[HY000] [1049] Unknown database 'symfony'

  [PDOException]
  SQLSTATE[HY000] [1049] Unknown database 'symfony'
```

**Comment by markitosgv** [comment]
is solved in DBAL 2.5.1?

**Comment by stof** [comment]
no. Read the release announcement. They explicitly mention that they don't have an appropriate fix yet

**Comment by markitosgv** [comment]
thanks @stof still waiting then

**Comment by PuReWebDev** [comment]
Just wanted mention this issue still exists and the pull request associated with the above closed ticket did not get accepted, so the issue is still present. Thank you guys for opening the issue and bringing it to the attention of the appropriate devs. Found the page as I also was experiencing the same.

**Comment by deudjuimw** [comment]
Hi all. Has the issue already been resolved or is there a workaround. Actually I'm following a tutorial with and facing the same error...

**Comment by stof** [comment]
See https://github.com/doctrine/DoctrineBundle/issues/351#issuecomment-65771528 for the workaround

**Comment by deudjuimw** [comment]
Ok, thank you !!!

**Comment by Tobion** [comment]
Closing as the issue is resolved. I'm not getting that error anymore when using the latest versions.
I guess the underlying problem is still open http://www.doctrine-project.org/jira/browse/DBAL-1057 but that doesn't affect the use-case of this ticket anymore.

**Comment by xabbuh** [comment]
@Tobion Currently, we [explicitly forbid doctrine/dbal 2.5.x](https://github.com/symfony/symfony-standard/blob/2.7/composer.json#L13) because of that issue. I suggest to keep this open as a reminder to allow it again once the referenced issue has been solved.

**Comment by Tobion** [comment]
I think we can allow dbal 2.5 again now. The common case to use repositories as services doesn't cause any problems anymore. DBAL-1057 might only affect some edge cases.

**Comment by Pierstoval** [comment]
Which explicit version should be avoided then?

**Comment by Tobion** [comment]
I think it's a combination of DBAL and ORM. The following should be fine
- DBAL 2.5 with ORM 2.5
- DBAL 2.5 with ORM >= 2.4.8 (which has not been release yet, it requires https://github.com/doctrine/doctrine2/commit/e05930e71482df06982c332b8820a1ae51bd7f28 to be tagged I guess)

**Comment by weaverryan** [comment]
It merits some testing, but I agree with Tobion - last time I checked, I couldn't repeat the issue. It would be *great* to not restrict 2.5 again.

**Comment by Tobion** [comment]
See #800
